name: Manual Build SDK (v3) For the Specific Target

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Choose Target
        default: 'all'
        options:
        - 'all'
        - 'esp32'
        - 'esp32s2'
        - 'esp32s3'
        - 'esp32c3'
        - 'esp32c6'
        - 'esp32h6'
        - 'esp32p4'
      log_level:
        type: choice
        description: Choose Log Level
        default: 'default'
        options:
        - 'default'
        - 'none'
        - 'verbose'
        - 'debug'
        - 'info'
        - 'warning'
        - 'error'

jobs:
  run:
    name: Build ${{ github.ref_name }} SDK (v3) For ${{ github.event.inputs.target }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: bash ./tools/prepare-ci.sh

      - name: Build
        shell: bash
        run: |
          export TARGET_TYPE=${{ github.event.inputs.target }}
          export LOG_LEVEL=${{ github.event.inputs.log_level }}
          echo "Building for $TARGET_TYPE (log_level: $LOG_LEVEL)"
          bash ./build.sh -e -t $TARGET_TYPE -D $LOG_LEVEL

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist