name: Build and push Docker image

on:
  push:
    branches:
      - 'master'
      - 'release/*'
    tags:
      - 'v*.*'
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      - "tools/config_editor/requirements.txt"
      - "tools/docker/Dockerfile"
      - "tools/docker/entrypoint.sh"

env:
  # Build the image for amd64 and arm64
  BUILD_PLATFORMS: linux/amd64,linux/arm64
  DOCKERHUB_REPO: ${{ github.repository_owner }}/esp32-arduino-lib-builder

jobs:
  docker:
    # Disable the job in forks
    if: ${{ github.event_name == 'pull_request' || github.repository_owner == 'espressif' }}
    name: Build docker image and push if needed
    runs-on: ubuntu-latest
    steps:
      # Depending on the branch/tag, set CLONE_BRANCH_OR_TAG variable (used in the Dockerfile
      # as a build arg) and TAG_NAME (used when tagging the image).
      #
      # The following 3 steps cover the alternatives (tag, release branch, master branch):
      - name: Set variables (tags)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo "CLONE_BRANCH_OR_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "TAG_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "URL=${{ github.server_url }}/${{ github.repository }}.git" >> $GITHUB_ENV

      - name: Set variables (release branches)
        if: ${{ github.ref_type == 'branch' && startsWith(github.ref_name, 'release/') }}
        run: |
          echo "CLONE_BRANCH_OR_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "TAG_NAME=release-${GITHUB_REF_NAME##release/}" >> $GITHUB_ENV
          echo "URL=${{ github.server_url }}/${{ github.repository }}.git" >> $GITHUB_ENV

      - name: Set variables (main branch)
        if: ${{ github.ref_type == 'branch' && github.ref_name == 'master' }}
        run: |
          echo "CLONE_BRANCH_OR_TAG=master" >> $GITHUB_ENV
          echo "TAG_NAME=latest" >> $GITHUB_ENV
          echo "URL=${{ github.server_url }}/${{ github.repository }}.git" >> $GITHUB_ENV

      - name: Set variables (pull requests)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "CLONE_BRANCH_OR_TAG=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "TAG_NAME=PR_${{ github.event.number }}" >> $GITHUB_ENV
          echo "URL=${{ github.server_url }}/${{ github.event.pull_request.head.repo.full_name }}.git" >> $GITHUB_ENV

      # Display the variables set above, just in case.
      - name: Check variables
        run: |
          echo "CLONE_BRANCH_OR_TAG: $CLONE_BRANCH_OR_TAG"
          echo "TAG_NAME: $TAG_NAME"
          echo "URL: $URL"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU for multiarch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: tools/docker
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.TAG_NAME }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          build-args: |
            LIBBUILDER_CLONE_URL=${{ env.URL }}
            LIBBUILDER_CLONE_BRANCH_OR_TAG=${{ env.CLONE_BRANCH_OR_TAG }}

      - name: Update Docker Hub repository description (master branch)
        if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master' }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_REPO }}
          readme-filepath: ./tools/docker/README.md
