name: Build and push Docker image

on:
  push:
    branches:
      - 'master'
      - 'release/*'
    tags:
      - 'v*.*'
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      - "tools/config_editor/requirements.txt"
      - "tools/docker/Dockerfile"
      - "tools/docker/entrypoint.sh"

env:
  # Build the image for amd64 and arm64
  BUILD_PLATFORMS: linux/amd64,linux/arm64
  DOCKERHUB_REPO: ${{ github.repository_owner }}/esp32-arduino-lib-builder

jobs:
  docker:
    # Disable the job in forks
    if: ${{ github.event_name == 'pull_request' || github.repository_owner == 'espressif' }}
    name: Build docker image and push if needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Depending on the branch/tag, set CLONE_BRANCH_OR_TAG variable (used in the Dockerfile
      # as a build arg) and DOCKER_TAGS (used when tagging the image).
      #
      # The following 3 steps cover the alternatives (tag, release branch, master branch):
      - name: Set variables (tags)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo "CLONE_BRANCH_OR_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "DOCKER_TAGS=${{ env.DOCKERHUB_REPO }}:$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "URL=${{ github.server_url }}/${{ github.repository }}.git" >> $GITHUB_ENV

      - name: Set variables (release branches)
        if: ${{ github.ref_type == 'branch' && startsWith(github.ref_name, 'release/') }}
        run: |
          echo "CLONE_BRANCH_OR_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "DOCKER_TAGS=${{ env.DOCKERHUB_REPO }}:release-${GITHUB_REF_NAME##release/}" >> $GITHUB_ENV
          echo "URL=${{ github.server_url }}/${{ github.repository }}.git" >> $GITHUB_ENV

      - name: Set variables (main branch)
        if: ${{ github.ref_type == 'branch' && github.ref_name == 'master' }}
        run: |
          source ./tools/config.sh
          echo "CLONE_BRANCH_OR_TAG=master" >> $GITHUB_ENV
          echo "DOCKER_TAGS<<EOF" >> $GITHUB_ENV
          echo "${{ env.DOCKERHUB_REPO }}:latest" >> $GITHUB_ENV
          echo "${{ env.DOCKERHUB_REPO }}:release-${IDF_BRANCH##release/}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "URL=${{ github.server_url }}/${{ github.repository }}.git" >> $GITHUB_ENV

      - name: Set variables (pull requests)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "CLONE_BRANCH_OR_TAG=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "DOCKER_TAGS=${{ env.DOCKERHUB_REPO }}:PR_${{ github.event.number }}" >> $GITHUB_ENV
          echo "URL=${{ github.server_url }}/${{ github.event.pull_request.head.repo.full_name }}.git" >> $GITHUB_ENV

      # Display the variables set above, just in case.
      - name: Check variables
        run: |
          echo "CLONE_BRANCH_OR_TAG: $CLONE_BRANCH_OR_TAG"
          echo "URL: $URL"
          echo "DOCKER_TAGS:"
          echo "$DOCKER_TAGS"

      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU for multiarch builds
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: tools/docker
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ env.DOCKER_TAGS }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          build-args: |
            LIBBUILDER_CLONE_URL=${{ env.URL }}
            LIBBUILDER_CLONE_BRANCH_OR_TAG=${{ env.CLONE_BRANCH_OR_TAG }}

      - name: Update Docker Hub repository description (master branch)
        if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master' }}
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_REPO }}
          readme-filepath: ./tools/docker/README.md
